{
 "title": "HC Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Number Of Subnets Created",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(eudico_node_stats_hc_subnet_created_count OR vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number Of Subnets Active (excl. /root)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(eudico_external_stats_hc_subnet_active_count-1 OR vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number Of Subnets Killed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(eudico_node_stats_hc_subnet_killed_count or on() vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95% Subnet Spin Up Time(ms)",
   "type": "gauge",
   "description": "The median subnet spin up time in millis seconds",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(eudico_node_stats_hc_subnet_start_duration_bucket[10m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}