version: '3'

services:
  prometheus:
    image: prom/prometheus
    network_mode: "host"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    network_mode: "host"
    ports:
      - "13000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana:/var/lib/grafana

volumes:
  influxdb:
  grafana:
