global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'service-monitoring'

rule_files: []

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['0.0.0.0:9090']
  - job_name: 'eudico-hc'
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: 'http'
    static_configs:
      - targets: [ '0.0.0.0:6688' ]
