// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package hierarchical

import (
	"fmt"
	"io"
	"math"
	"sort"

	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

var lengthBufConsensusParams = []byte{131}

func (t *ConsensusParams) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufConsensusParams); err != nil {
		return err
	}

	// t.Alg (hierarchical.ConsensusType) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Alg)); err != nil {
		return err
	}

	// t.DelegMiner (address.Address) (struct)
	if err := t.DelegMiner.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.MinValidators (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.MinValidators)); err != nil {
		return err
	}

	return nil
}

func (t *ConsensusParams) UnmarshalCBOR(r io.Reader) (err error) {
	*t = ConsensusParams{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 3 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Alg (hierarchical.ConsensusType) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.Alg = ConsensusType(extra)

	}
	// t.DelegMiner (address.Address) (struct)

	{

		if err := t.DelegMiner.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.DelegMiner: %w", err)
		}

	}
	// t.MinValidators (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.MinValidators = uint64(extra)

	}
	return nil
}

var lengthBufValidator = []byte{131}

func (t *Validator) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufValidator); err != nil {
		return err
	}

	// t.Subnet (address.SubnetID) (struct)
	if err := t.Subnet.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.Addr (address.Address) (struct)
	if err := t.Addr.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.NetAddr (string) (string)
	if len(t.NetAddr) > cbg.MaxLength {
		return xerrors.Errorf("Value in field t.NetAddr was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.NetAddr))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string(t.NetAddr)); err != nil {
		return err
	}
	return nil
}

func (t *Validator) UnmarshalCBOR(r io.Reader) (err error) {
	*t = Validator{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 3 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.Subnet (address.SubnetID) (struct)

	{

		if err := t.Subnet.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.Subnet: %w", err)
		}

	}
	// t.Addr (address.Address) (struct)

	{

		if err := t.Addr.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.Addr: %w", err)
		}

	}
	// t.NetAddr (string) (string)

	{
		sval, err := cbg.ReadString(cr)
		if err != nil {
			return err
		}

		t.NetAddr = string(sval)
	}
	return nil
}
