// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package hierarchical

import (
	"fmt"
	"io"
	"math"
	"sort"

	"github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	"golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

var lengthBufConsensusParams = []byte{130}

func (t *ConsensusParams) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	if _, err := w.Write(lengthBufConsensusParams); err != nil {
		return err
	}

	scratch := make([]byte, 9)

	// t.DelegMiner (address.Address) (struct)
	if err := t.DelegMiner.MarshalCBOR(w); err != nil {
		return err
	}

	// t.MinValidators (uint64) (uint64)

	if err := cbg.WriteMajorTypeHeaderBuf(scratch, w, cbg.MajUnsignedInt, uint64(t.MinValidators)); err != nil {
		return err
	}

	return nil
}

func (t *ConsensusParams) UnmarshalCBOR(r io.Reader) error {
	*t = ConsensusParams{}

	br := cbg.GetPeeker(r)
	scratch := make([]byte, 8)

	maj, extra, err := cbg.CborReadHeaderBuf(br, scratch)
	if err != nil {
		return err
	}
	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 2 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.DelegMiner (address.Address) (struct)

	{

		if err := t.DelegMiner.UnmarshalCBOR(br); err != nil {
			return xerrors.Errorf("unmarshaling t.DelegMiner: %w", err)
		}

	}
	// t.MinValidators (uint64) (uint64)

	{

		maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.MinValidators = uint64(extra)

	}
	return nil
}

