// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package resolver

import (
	"fmt"
	"io"
	"math"
	"sort"

	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

var lengthBufResolveMsg = []byte{134}

func (t *ResolveMsg) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufResolveMsg); err != nil {
		return err
	}

	// t.From (address.SubnetID) (struct)
	if err := t.From.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.Type (resolver.MsgType) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Type)); err != nil {
		return err
	}

	// t.Cid (cid.Cid) (struct)

	if err := cbg.WriteCid(cw, t.Cid); err != nil {
		return xerrors.Errorf("failed to write cid field t.Cid: %w", err)
	}

	// t.CrossMsgs (sca.CrossMsgs) (struct)
	if err := t.CrossMsgs.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.Locked (atomic.LockedState) (struct)
	if err := t.Locked.MarshalCBOR(cw); err != nil {
		return err
	}

	// t.Actor (string) (string)
	if len(t.Actor) > cbg.MaxLength {
		return xerrors.Errorf("Value in field t.Actor was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.Actor))); err != nil {
		return err
	}
	if _, err := io.WriteString(w, string(t.Actor)); err != nil {
		return err
	}
	return nil
}

func (t *ResolveMsg) UnmarshalCBOR(r io.Reader) (err error) {
	*t = ResolveMsg{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 6 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.From (address.SubnetID) (struct)

	{

		if err := t.From.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.From: %w", err)
		}

	}
	// t.Type (resolver.MsgType) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.Type = MsgType(extra)

	}
	// t.Cid (cid.Cid) (struct)

	{

		c, err := cbg.ReadCid(cr)
		if err != nil {
			return xerrors.Errorf("failed to read cid field t.Cid: %w", err)
		}

		t.Cid = c

	}
	// t.CrossMsgs (sca.CrossMsgs) (struct)

	{

		if err := t.CrossMsgs.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.CrossMsgs: %w", err)
		}

	}
	// t.Locked (atomic.LockedState) (struct)

	{

		if err := t.Locked.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.Locked: %w", err)
		}

	}
	// t.Actor (string) (string)

	{
		sval, err := cbg.ReadString(cr)
		if err != nil {
			return err
		}

		t.Actor = string(sval)
	}
	return nil
}
