chmod 600 data/alice/keystore/*
chmod 600 data/bob/keystore/*
chmod 600 data/charlie/keystore/*
chmod 600 data/dom/keystore/*
chmod +x ./scripts/restart_bitcoin.sh
chmod +x ./scripts/delete_eudico_data.sh
chmod +x ./scripts/restart-demo.sh
chmod +x ./scripts/add-initial-mpower.sh
chmod +x ./scripts/add-dom-power.sh
chmod +x ./scripts/remove-dom-mpower.sh
chmod +x ./scripts/remove-charlie.sh
chmod +x ./scripts/genesis-newstate.sh
